import type { User, Match, Transaction, Comment, RosterPlayer } from '@/types';

// ─── Mock User ──────────────────────────────────────

export const mockUser: User = {
    id: 'usr_001',
    fullName: 'Ahmed Al-Farsi',
    handle: '@ahmed_farsi',
    avatarUrl: '/images/avatars/ahmed.jpg',
    phone: '+966 5X XXX XXXX',
    preferredLocation: 'Riyadh',
    preferredPosition: 'Midfielder',
    skillLevel: 'intermediate',
    locale: 'ar',
};

// ─── Mock Roster Players ────────────────────────────

const rosterPool: RosterPlayer[] = [
    { id: 'rp1', name: 'Yousef K.', avatarUrl: '/images/avatars/p1.jpg' },
    { id: 'rp2', name: 'Omar S.', avatarUrl: '/images/avatars/p2.jpg' },
    { id: 'rp3', name: 'Fahad M.', avatarUrl: '/images/avatars/p3.jpg' },
    { id: 'rp4', name: 'Ali R.', avatarUrl: '/images/avatars/p4.jpg' },
    { id: 'rp5', name: 'Khalid A.', avatarUrl: '/images/avatars/p5.jpg' },
    { id: 'rp6', name: 'Nasser H.', avatarUrl: '/images/avatars/p6.jpg' },
    { id: 'rp7', name: 'Sultan T.', avatarUrl: '/images/avatars/p7.jpg' },
    { id: 'rp8', name: 'Turki B.', avatarUrl: '/images/avatars/p8.jpg' },
    { id: 'rp9', name: 'Abdulaziz D.', avatarUrl: '/images/avatars/p9.jpg' },
    { id: 'rp10', name: 'Majed W.', avatarUrl: '/images/avatars/p10.jpg' },
    { id: 'rp11', name: 'Sami Q.', avatarUrl: '/images/avatars/p11.jpg' },
    { id: 'rp12', name: 'Hamad L.', avatarUrl: '/images/avatars/p12.jpg' },
    { id: 'rp13', name: 'Bader N.', avatarUrl: '/images/avatars/p13.jpg' },
    { id: 'rp14', name: 'Rayan F.', avatarUrl: '/images/avatars/p14.jpg' },
    { id: 'rp15', name: 'Faisal G.', avatarUrl: '/images/avatars/p15.jpg' },
    { id: 'rp16', name: 'Meshal V.', avatarUrl: '/images/avatars/p16.jpg' },
];

// ─── Mock Comments ──────────────────────────────────

const mockCommentsPool: Comment[] = [
    {
        id: 'cmt_1',
        userId: 'rp1',
        userName: 'Yousef K.',
        userAvatar: '/images/avatars/p1.jpg',
        text: 'Is there parking available near th...',
        createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(), // 2m ago
    },
    {
        id: 'cmt_2',
        userId: 'rp3',
        userName: 'Fahad M.',
        userAvatar: '/images/avatars/p3.jpg',
        text: 'Great pitch! See you all there 🏟️',
        createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    },
];

// ─── Mock Matches ───────────────────────────────────

export const mockMatches: Match[] = [
    {
        id: 'match_001',
        title: 'Night Owl Kickoff',
        organizer: {
            name: 'Ahmed Kora',
            handle: '@ahmed_kora',
            avatarUrl: '/images/avatars/org1.jpg',
            rating: 4.9,
        },
        date: new Date().toISOString().split('T')[0],
        time: '11:00 PM',
        endTime: '12:30 AM',
        location: 'Al Olaya, Riyadh',
        venueName: 'King Abdullah Park',
        venueDetails: 'Pitch 3, Riyadh',
        lat: 24.7136,
        lng: 46.6753,
        format: '7 vs 7',
        surface: 'Grass',
        gender: 'men',
        intensity: 'Mixed Skill',
        price: 37,
        currency: 'SAR',
        totalSpots: 16,
        filledSpots: 15,
        status: 'closing_soon',
        imageUrl: '/images/pitch-hero.jpg',
        rules: ['Bring water', 'No studs allowed'],
        roster: rosterPool.slice(0, 15),
        comments: mockCommentsPool,
    },
    {
        id: 'match_002',
        title: 'Casual Thursday',
        organizer: {
            name: 'Sarah Football',
            handle: '@sarah_football',
            avatarUrl: '/images/avatars/org2.jpg',
            rating: 4.7,
        },
        date: new Date().toISOString().split('T')[0],
        time: '08:00 PM',
        endTime: '09:30 PM',
        location: 'Jeddah',
        venueName: 'Corniche Arena',
        venueDetails: 'Main Pitch',
        lat: 21.4858,
        lng: 39.1925,
        format: '5 vs 5',
        surface: 'Artificial Turf',
        gender: 'mixed',
        intensity: 'Mixed Skill',
        price: 45,
        currency: 'SAR',
        totalSpots: 12,
        filledSpots: 4,
        status: 'open',
        imageUrl: '/images/pitch-hero.jpg',
        roster: rosterPool.slice(0, 4),
        comments: [],
    },
    {
        id: 'match_003',
        title: 'Competitive 5v5',
        organizer: {
            name: 'Dammam League',
            handle: '@dammam_league',
            avatarUrl: '/images/avatars/org3.jpg',
            rating: 4.8,
        },
        date: new Date().toISOString().split('T')[0],
        time: '09:30 PM',
        endTime: '11:00 PM',
        location: 'Dammam',
        venueName: 'Eastern Province Stadium',
        venueDetails: 'Pitch 1',
        lat: 26.3927,
        lng: 49.9777,
        format: '5 vs 5',
        surface: 'Artificial Turf',
        gender: 'men',
        intensity: 'High Intensity',
        price: 50,
        currency: 'SAR',
        totalSpots: 10,
        filledSpots: 9,
        status: 'closing_soon',
        imageUrl: '/images/pitch-hero.jpg',
        roster: rosterPool.slice(0, 9),
        comments: mockCommentsPool.slice(0, 1),
    },
    {
        id: 'match_004',
        title: 'Weekend Warriors',
        organizer: {
            name: 'Riyadh FC',
            handle: '@riyadh_fc',
            avatarUrl: '/images/avatars/org1.jpg',
            rating: 4.6,
        },
        date: new Date(Date.now() + 86400000).toISOString().split('T')[0],
        time: '06:00 PM',
        endTime: '07:30 PM',
        location: 'Al Malaz, Riyadh',
        venueName: 'Al Malaz Stadium',
        venueDetails: 'Mini Pitch B',
        format: '7 vs 7',
        surface: 'Grass',
        gender: 'men',
        intensity: 'Competitive',
        price: 55,
        currency: 'SAR',
        totalSpots: 14,
        filledSpots: 8,
        status: 'open',
        imageUrl: '/images/pitch-hero.jpg',
        roster: rosterPool.slice(0, 8),
        comments: [],
    },
    {
        id: 'match_005',
        title: 'Sunrise Session',
        organizer: {
            name: 'Morning FC',
            handle: '@morning_fc',
            avatarUrl: '/images/avatars/org2.jpg',
            rating: 4.5,
        },
        date: new Date(Date.now() + 2 * 86400000).toISOString().split('T')[0],
        time: '06:30 AM',
        endTime: '08:00 AM',
        location: 'King Fahd, Riyadh',
        venueName: 'King Fahd Sports City',
        venueDetails: 'Outdoor Pitch 2',
        format: '11 vs 11',
        surface: 'Grass',
        gender: 'men',
        intensity: 'Mixed Skill',
        price: 30,
        currency: 'SAR',
        totalSpots: 22,
        filledSpots: 14,
        status: 'open',
        imageUrl: '/images/pitch-hero.jpg',
        roster: rosterPool.slice(0, 14),
        comments: [],
    },
];

// ─── Mock Transactions ──────────────────────────────

export const mockTransactions: Transaction[] = [
    {
        id: 'txn_001',
        type: 'debit',
        category: 'match_payment',
        title: 'Night Owl Kickoff',
        description: '19:30 • Successful',
        amount: 45.0,
        currency: 'SAR',
        createdAt: new Date().toISOString(),
        icon: 'match',
    },
    {
        id: 'txn_002',
        type: 'credit',
        category: 'topup',
        title: 'Wallet Top Up',
        description: '14:20 • Credit Card •• 42',
        amount: 200.0,
        currency: 'SAR',
        createdAt: new Date().toISOString(),
        icon: 'wallet',
    },
    {
        id: 'txn_003',
        type: 'credit',
        category: 'refund',
        title: 'Refund - Weekend Derby',
        description: 'Nov 12 • Canceled Match',
        amount: 45.0,
        currency: 'SAR',
        createdAt: new Date(Date.now() - 86400000).toISOString(),
        icon: 'refund',
    },
    {
        id: 'txn_004',
        type: 'debit',
        category: 'store_purchase',
        title: 'Pro Store Gear',
        description: 'Nov 12 • Gloves & Socks',
        amount: 120.0,
        currency: 'SAR',
        createdAt: new Date(Date.now() - 86400000).toISOString(),
        icon: 'store',
    },
    {
        id: 'txn_005',
        type: 'debit',
        category: 'match_payment',
        title: 'Friday League Match',
        description: 'Nov 10 • Successful',
        amount: 60.0,
        currency: 'SAR',
        createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
        icon: 'match',
    },
];

// ─── Helpers ────────────────────────────────────────

export const mockWalletBalance = 150.0;
